# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'function.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_function(object):
    def setupUi(self, function):
        function.setObjectName("function")
        function.resize(768, 512)
        function.setMinimumSize(QtCore.QSize(768, 512))
        function.setMaximumSize(QtCore.QSize(768, 512))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        function.setFont(font)
        self.func = QtWidgets.QFrame(function)
        self.func.setGeometry(QtCore.QRect(30, 20, 701, 461))
        self.func.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.func.setFrameShadow(QtWidgets.QFrame.Raised)
        self.func.setObjectName("func")
        self.pushButton_next = QtWidgets.QPushButton(self.func)
        self.pushButton_next.setGeometry(QtCore.QRect(500, 420, 121, 41))
        self.pushButton_next.setObjectName("pushButton_next")
        self.pushButton_back = QtWidgets.QPushButton(self.func)
        self.pushButton_back.setGeometry(QtCore.QRect(70, 420, 121, 41))
        self.pushButton_back.setObjectName("pushButton_back")
        self.scrollArea = QtWidgets.QScrollArea(self.func)
        self.scrollArea.setGeometry(QtCore.QRect(460, 60, 181, 281))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scrollArea.setFont(font)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 158, 357))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_sphere = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_sphere.setObjectName("checkBox_sphere")
        self.verticalLayout.addWidget(self.checkBox_sphere)
        self.checkBox_ai = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_ai.setObjectName("checkBox_ai")
        self.verticalLayout.addWidget(self.checkBox_ai)
        self.checkBox_filter = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_filter.setObjectName("checkBox_filter")
        self.verticalLayout.addWidget(self.checkBox_filter)
        self.checkBox_cone = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_cone.setObjectName("checkBox_cone")
        self.verticalLayout.addWidget(self.checkBox_cone)
        self.checkBox_blower = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_blower.setObjectName("checkBox_blower")
        self.verticalLayout.addWidget(self.checkBox_blower)
        self.checkBox_fan = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_fan.setObjectName("checkBox_fan")
        self.verticalLayout.addWidget(self.checkBox_fan)
        self.checkBox_evap = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_evap.setObjectName("checkBox_evap")
        self.verticalLayout.addWidget(self.checkBox_evap)
        self.checkBox_heater = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_heater.setObjectName("checkBox_heater")
        self.verticalLayout.addWidget(self.checkBox_heater)
        self.checkBox_distributor = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_distributor.setObjectName("checkBox_distributor")
        self.verticalLayout.addWidget(self.checkBox_distributor)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton_CG = QtWidgets.QPushButton(self.func)
        self.pushButton_CG.setGeometry(QtCore.QRect(70, 60, 201, 121))
        self.pushButton_CG.setObjectName("pushButton_CG")
        self.label_3 = QtWidgets.QLabel(self.func)
        self.label_3.setGeometry(QtCore.QRect(450, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.func)
        self.label.setEnabled(False)
        self.label.setGeometry(QtCore.QRect(140, 260, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.func)
        self.label_2.setGeometry(QtCore.QRect(130, 120, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_XX = QtWidgets.QPushButton(self.func)
        self.pushButton_XX.setEnabled(False)
        self.pushButton_XX.setGeometry(QtCore.QRect(70, 200, 201, 121))
        self.pushButton_XX.setObjectName("pushButton_XX")
        self.toolButton_cool = QtWidgets.QToolButton(self.func)
        self.toolButton_cool.setGeometry(QtCore.QRect(230, 60, 41, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("cool.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_cool.setIcon(icon)
        self.toolButton_cool.setIconSize(QtCore.QSize(40, 40))
        self.toolButton_cool.setObjectName("toolButton_cool")
        self.toolButton_hot = QtWidgets.QToolButton(self.func)
        self.toolButton_hot.setGeometry(QtCore.QRect(230, 140, 41, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("hot.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_hot.setIcon(icon1)
        self.toolButton_hot.setIconSize(QtCore.QSize(40, 40))
        self.toolButton_hot.setObjectName("toolButton_hot")
        self.label_4 = QtWidgets.QLabel(self.func)
        self.label_4.setGeometry(QtCore.QRect(70, 340, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.func)
        self.label_5.setGeometry(QtCore.QRect(60, 30, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_next.raise_()
        self.pushButton_back.raise_()
        self.scrollArea.raise_()
        self.pushButton_CG.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.pushButton_XX.raise_()
        self.label.raise_()
        self.toolButton_cool.raise_()
        self.toolButton_hot.raise_()
        self.label_4.raise_()
        self.label_5.raise_()

        self.retranslateUi(function)
        # self.pushButton_CG.clicked.connect(self.toolButton_cool.raise)
        QtCore.QMetaObject.connectSlotsByName(function)

    def retranslateUi(self, function):
        _translate = QtCore.QCoreApplication.translate
        function.setWindowTitle(_translate("function", "功能"))
        self.pushButton_next.setText(_translate("function", "next"))
        self.pushButton_back.setText(_translate("function", "back"))
        self.checkBox_sphere.setText(_translate("function", "sphere"))
        self.checkBox_ai.setText(_translate("function", "ai"))
        self.checkBox_filter.setText(_translate("function", "filter"))
        self.checkBox_cone.setText(_translate("function", "cone"))
        self.checkBox_blower.setText(_translate("function", "blower"))
        self.checkBox_fan.setText(_translate("function", "fan"))
        self.checkBox_evap.setText(_translate("function", "evap"))
        self.checkBox_heater.setText(_translate("function", "heater"))
        self.checkBox_distributor.setText(_translate("function", "distributor"))
        self.pushButton_CG.setText(_translate("function", "常规\n"))
        self.label_3.setText(_translate("function", "check:"))
        self.label.setText(_translate("function", "（未启用）"))
        self.label_2.setText(_translate("function", "（分配、压降）"))
        self.pushButton_XX.setText(_translate("function", "线性\n"))
        self.toolButton_cool.setText(_translate("function", "..."))
        self.toolButton_hot.setText(_translate("function", "..."))
        self.label_4.setText(_translate("function", "注意：1、常规模式默认不启用heater，若需启用，请点击hot按钮。\n"
                                                    "          2、线性功能暂未启用"))
        self.label_5.setText(_translate("function", "quickly"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QWidget()
    ui = Ui_function()  # 这里改成你自己的项目名称，如果你没特意改过，就默认就行
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())
